/* MIDTOWN DENTAL — SHARED JS */
function toggleMobileNav(){document.getElementById('mobile-nav').classList.toggle('open');}
function initFadeIn(){const obs=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible');});},{threshold:0.1});document.querySelectorAll('.fade-in').forEach(el=>obs.observe(el));}
function submitBooking(formId){const form=document.getElementById(formId);if(!form)return;const name=form.querySelector('[name="patient-name"]');const phone=form.querySelector('[name="phone"]');if(!name?.value.trim()||!phone?.value.trim()){alert('Please enter your name and phone number.');return;}const successEl=form.querySelector('.form-success-msg');if(successEl){successEl.style.display='block';successEl.innerHTML='✅ Thank you, <strong>'+name.value+'</strong>! We will call you at <strong>'+phone.value+'</strong> to confirm your appointment.';form.querySelector('.btn-book').style.display='none';}}
function initFAQs(){document.querySelectorAll('.faq-q').forEach(q=>{q.addEventListener('click',()=>{const item=q.closest('.faq-item');const isOpen=item.classList.contains('open');document.querySelectorAll('.faq-item').forEach(f=>f.classList.remove('open'));if(!isOpen)item.classList.add('open');});});}

const CHAT_KB={greetings:['hello','hi','hey','namaste','good morning'],hours:['open','hour','time','schedule','when','close','timing'],location:['where','location','address','map','find','prithvi','pokhara'],services:['service','treatment','braces','ortho','filling','scaling','surgery','cleaning','whitening','implant','root','crown','extract'],cost:['cost','price','fee','charge','how much','rate','affordable'],book:['book','appointment','visit','schedule','reserve'],rating:['rating','review','google','star','feedback','recommend'],emergency:['emergency','pain','hurt','toothache','urgent','bleeding'],team:['doctor','dentist','team','staff','hygienist'],sterilize:['clean','sterile','hygiene','safe','sanitize']};
const CHAT_RESPONSES={greetings:"Hi there! 👋 Welcome to Midtown Dental. I'm here to help you with appointments, services, location, and more. How can I assist you?",hours:"We're open <strong>Tuesday to Sunday from 9:30 AM</strong>. We're appointment-based so there's zero crowd — just calm, comfortable care. Want to book? 📅",location:"We're at <strong>Prithvi Chowk, Pokhara, Nepal</strong> — right in Midtown. Easy to find! Call us at <strong>061-585333</strong> for directions.",services:"We offer:<br>🦷 Orthodontics (Braces &amp; Aligners)<br>🪥 Scaling &amp; Polishing<br>🔧 Cavity Fillings<br>✂️ Oral Surgery &amp; Extractions<br>⚡ Root Canal Treatment<br>🦴 Dental Implants<br>✨ Teeth Whitening<br>Which service interests you?",cost:"Our prices are affordable and transparent — no hidden fees. Exact cost depends on the treatment. We recommend a free consultation to get a clear estimate. Want to schedule one? 😊",book:"Book an appointment:<br>📞 Call <strong>061-585333</strong><br>🌐 Use our <strong>Book Appointment</strong> page<br>We're appointment-based so you get our full attention — no waiting!",rating:"We're rated <strong>4.9/5 on Google Maps</strong> with 66+ glowing reviews! 🌟 Patients love our clean space, friendly team, and painless procedures.",emergency:"Please call <strong>📞 061-585333</strong> immediately! Dental emergencies are our priority — we'll fit you in as fast as possible. 🦷",team:"Our team of friendly dentists, orthodontists, and hygienists treat you like family. Learn more on our <strong>About</strong> page!",sterilize:"Patient safety is our #1 priority. <strong>100% of tools are sterilized</strong> between every patient. Our clinic is spotless and safe. ✅",default:"Happy to help! Ask me about our <strong>services</strong>, <strong>location</strong>, <strong>hours</strong>, or how to <strong>book</strong>. Or call <strong>061-585333</strong> directly. 😊"};
function detectIntent(text){const lower=text.toLowerCase();for(const[intent,keywords]of Object.entries(CHAT_KB)){if(keywords.some(k=>lower.includes(k)))return intent;}return 'default';}
let chatOpen=false;
function toggleChat(){chatOpen=!chatOpen;const win=document.getElementById('chat-window');if(chatOpen){win.classList.add('open');const n=document.querySelector('#chat-bubble .notif');if(n)n.style.display='none';}else{win.classList.remove('open');}}
function sendChatMsg(text){if(!text){const input=document.getElementById('chat-input');text=input?.value.trim();if(!text)return;if(input)input.value='';}const msgs=document.getElementById('chat-msgs');if(!msgs)return;const userDiv=document.createElement('div');userDiv.className='chat-msg user';userDiv.textContent=text;msgs.appendChild(userDiv);msgs.scrollTop=msgs.scrollHeight;setTimeout(()=>{const intent=detectIntent(text);const response=CHAT_RESPONSES[intent]||CHAT_RESPONSES.default;const botDiv=document.createElement('div');botDiv.className='chat-msg bot';botDiv.innerHTML=response;msgs.appendChild(botDiv);msgs.scrollTop=msgs.scrollHeight;},700);}
function chatQuickReply(text){sendChatMsg(text);}
function chatKeyPress(e){if(e.key==='Enter')sendChatMsg();}
function animateCounters(){document.querySelectorAll('[data-count]').forEach(el=>{const target=parseFloat(el.dataset.count);const suffix=el.dataset.suffix||'';const duration=1500,steps=60,increment=target/steps;let current=0;const timer=setInterval(()=>{current+=increment;if(current>=target){current=target;clearInterval(timer);}el.textContent=(Number.isInteger(target)?Math.floor(current):current.toFixed(1))+suffix;},duration/steps);});}
document.addEventListener('DOMContentLoaded',()=>{initFadeIn();initFAQs();const counterEl=document.querySelector('[data-count]');if(counterEl){const obs=new IntersectionObserver(entries=>{if(entries[0].isIntersecting){animateCounters();obs.disconnect();}},{threshold:0.3});obs.observe(counterEl.closest('section')||counterEl);}});
